trigger:
- master

jobs:
  - job: "DotNet"
    pool: Default

    steps:
    - checkout: self
      submodules: recursive

    - bash: dotnet restore --no-cache --verbosity normal
      displayName: Restore

    - bash: dotnet build --no-restore --configuration Release
      displayName: Build

    - bash: dotnet test --configuration Release --no-build
      displayName: Test



